### ISSUE TITLE
Create a Docker image for the project

### ISSUE THREAD

**Issue by kxlt** [kxlt/imageresizer#17]
Create a Docker image for the project. It should integrate libvips 8.5+ and this program. Use a minimal base image such as alpine.

Expose the environment variables and the volumes you deem necessary.

**Comment by disisisid** [comment]
Hey, I'd like to take a crack at this.

**Comment by kxlt** [comment]
Go ahead!

**Comment by HannanSolo** [comment]
Mind if I get a swing at this for one of those tasty hacktoberfest points?

**Comment by kxlt** [comment]
Go ahead! I create these issues for hacktoberfest participants :)

**Comment by sr6033** [comment]
A simple version - #18
