### ISSUE TITLE
Add storage support for DigitalOcean Spaces

### ISSUE THREAD

**Issue by sudokai** [kxlt/imageresizer#5]
We currently support local filesystem and S3 storage for original images. Add a similar bridge for DigitalOcean Spaces, by implementing the [`store.Store`](https://github.com/kxlt/imageresizer/blob/master/store/store.go#L3) interface and exposing the config properties you deem necessary.

**Comment by dnivra26** [comment]
Hi @kxlt, i would like to work on this

**Comment by kxlt** [comment]
Perfect! This project is in very young and I don't have a contributor's guide, but go ahead and open a PR! Thank you for working on this!

**Comment by kxlt** [comment]
@dnivra26 Any updates? Please remember that tomorrow October 31st is the last day for Hacktoberfest submissions.

**Comment by dnivra26** [comment]
@kxlt sorry for the delay. it seems dropbox space is compatible with any S3 client. So do we need a separate store? And even in their official go lang client the recommended approach for spaces is to use an S3 client.

**Comment by kxlt** [comment]
@dnivra26 Oh, I see. I haven't use DO Spaces myself but thought it would be nice to support a cheaper alternative to S3.

I will open an issue to add support to Google Cloud Storage though.
